[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

#[programs.localnet]
#dg_solana_programs = "DxzbvkdnQhXGmEz732meAeF9TS8qLit7SAcpa6JXnB6P"

[programs.devnet]
dg_solana_programs = "j3q33yPf3b74tKkXepzcK5oZ45ULgCUpAjtxXWfUF1z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet" ## Use mainnet for test purpose
wallet = "~/.config/solana/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
