[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dg_solana_zapin = "2f7mzs8Hqra1L6aLCEdoR4inNtNBFmNgsiuJMr8q2x7A"

[programs.mainnet]
dg_solana_zapin = "2f7mzs8Hqra1L6aLCEdoR4inNtNBFmNgsiuJMr8q2x7A"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
