[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dg_solana_zapin = "86dsQeMpQW5m1LpyPQ1Ss7GpViW3moUwF5YsPH1ibFee"

[programs.mainnet]
dg_solana_zapin = "DgrQqeR5MTFkNNG94siEd5cDxdzgexSNwbv4FHdNW8f3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
