[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dg_solana_zapin = "2h2KDqUHkHf7DVUd3SJCeEPPLMLiYuviojp3YFJgMnZN"

[programs.mainnet]
dg_solana_zapin = "2h2KDqUHkHf7DVUd3SJCeEPPLMLiYuviojp3YFJgMnZN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
